server:
  port: 9001
  servlet:
    context-path: /myMicroService
spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.211.55.4:8848
#  application:
#    name: my-microservice-provider-dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://10.211.55.4:3306/hello?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            max-active: 20
            min-idle: 10
            max-wait: 3000
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            poolName: pdamanagerDB
#        slave_1:
#            url: jdbc:mysql://10.211.55.5:3316/hello?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#            username: root
#            password: root
#            driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#            type: com.alibaba.druid.pool.DruidDataSource
#            druid:
#              initial-size: 5
#              max-active: 20
#              min-idle: 10
#              max-wait: 3000
#              min-evictable-idle-time-millis: 30000
#              max-evictable-idle-time-millis: 30000
      druid:
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
